--
-- PostgreSQL database dump
--

\restrict nqRtHBaaKAIjGibYCgBPjtcnAhp9tOhFSdICs6bV82HHP5c54ekafNubFcTUvaJ

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public.cliente (
    client_id character varying(255),
    estado boolean,
    password character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.cliente OWNER TO bankuser;

--
-- Name: cuenta; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public.cuenta (
    cuenta_id bigint NOT NULL,
    estado boolean,
    numero_cuenta character varying(255),
    saldo_inicial numeric(38,2),
    tipo_cuenta character varying(255),
    cliente_id bigint,
    CONSTRAINT cuenta_tipo_cuenta_check CHECK (((tipo_cuenta)::text = ANY ((ARRAY['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[])))
);


ALTER TABLE public.cuenta OWNER TO bankuser;

--
-- Name: cuenta_cuenta_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public.cuenta ALTER COLUMN cuenta_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_cuenta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimiento; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public.movimiento (
    id bigint NOT NULL,
    fecha date,
    saldo numeric(38,2),
    tipo_movimiento character varying(255),
    valor numeric(38,2),
    cuenta_id bigint,
    CONSTRAINT movimiento_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['RETIRO'::character varying, 'DEPOSITO'::character varying])::text[])))
);


ALTER TABLE public.movimiento OWNER TO bankuser;

--
-- Name: movimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public.movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: bankuser
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    direccion character varying(255) NOT NULL,
    edad integer,
    genero character varying(255) NOT NULL,
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    CONSTRAINT persona_edad_check CHECK (((edad >= 0) AND (edad <= 100)))
);


ALTER TABLE public.persona OWNER TO bankuser;

--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: bankuser
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (cuenta_id);


--
-- Name: movimiento movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: cliente uk3k6to0v3rwqwqpyraa71sjdqs; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT uk3k6to0v3rwqwqpyraa71sjdqs UNIQUE (client_id);


--
-- Name: cuenta ukpj7ncg765kt4klndu25bwbwe4; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT ukpj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta);


--
-- Name: persona ukr5vsms84ih2viwd6tatk9o5pq; Type: CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion);


--
-- Name: movimiento fk4ea11fe7p3xa1kwwmdgi9f2fi; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT fk4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(cuenta_id);


--
-- Name: cuenta fk4p224uogyy5hmxvn8fwa2jlug; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT fk4p224uogyy5hmxvn8fwa2jlug FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: cliente fkkpvkbjg32bso6riqge70hwcel; Type: FK CONSTRAINT; Schema: public; Owner: bankuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fkkpvkbjg32bso6riqge70hwcel FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- PostgreSQL database dump complete
--

\unrestrict nqRtHBaaKAIjGibYCgBPjtcnAhp9tOhFSdICs6bV82HHP5c54ekafNubFcTUvaJ

